import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { findGitSubcommandIndex, findNpmSubcommandIndex } from "./command-shape.js";

const CLAUDE_MARKER = "@CONTEXT_RELAY.md";
const CODEX_MARKER = "@CONTEXT_RELAY.md";
const MANAGED_START = "# --- Context Relay managed block ---";
const MANAGED_END = "# --- end Context Relay managed block ---";

const SAFE_COMMANDS = new Set([
  "bun",
  "cargo",
  "deno",
  "find",
  "git",
  "grep",
  "jest",
  "make",
  "node",
  "npm",
  "pnpm",
  "pytest",
  "rg",
  "tsc",
  "yarn",
]);

const FINITE_PACKAGE_SUBCOMMANDS = new Set(["build", "check", "lint", "test", "typecheck", "type-check"]);
const FINITE_BUN_SUBCOMMANDS = new Set(["test"]);
const FINITE_CARGO_SUBCOMMANDS = new Set(["build", "check", "clippy", "test"]);
const FINITE_DENO_SUBCOMMANDS = new Set(["check", "lint", "test"]);
const FINITE_YARN_SUBCOMMANDS = new Set(["build", "check", "lint", "test", "typecheck", "type-check"]);

const SKIP_COMMANDS = new Set([
  "claude",
  "codex",
  "context-relay",
  "curl",
  "gh",
  "htop",
  "less",
  "more",
  "nano",
  "open",
  "scp",
  "ssh",
  "sudo",
  "tail",
  "top",
  "vim",
  "vi",
  "watch",
  "wget",
]);

const AUTH_PATTERNS = [
  /\blogin\b/i,
  /\bauth\b/i,
  /\btoken\b/i,
  /\bsecret\b/i,
  /\bpassword\b/i,
  /\bpasswd\b/i,
  /\bcredential/i,
];

const INTERACTIVE_OR_LONG_RUNNING_PATTERNS = [
  /\b--watch\b/i,
  /\bwatch\b/i,
  /\bdev\b/i,
  /\bserve\b/i,
  /\bserver\b/i,
  /\bstart\b/i,
  /\binit\b/i,
  /\bcreate\b/i,
  /\bpublish\b/i,
  /\brelease\b/i,
  /\bpreview\b/i,
  /\bdaemon\b/i,
  /\brepl\b/i,
];

const SAFE_GIT_SUBCOMMANDS = new Set([
  "blame",
  "branch",
  "diff",
  "grep",
  "log",
  "ls-files",
  "show",
  "status",
]);
const SHELL_CONTROL_OPERATOR_PATTERN = /&&|\|\||[|;&]/;

export function shellQuote(value) {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

// The hook a PreToolUse handler executes runs as a detached subprocess that does NOT
// inherit the invoking shell's PATH (e.g. a login-shell nvm PATH). A bare "context-relay
// hook claude" therefore silently fails to resolve on any machine where context-relay was
// installed via `npm link` from a local clone, rather than a global npm install onto a
// PATH directory. Resolve an absolute, self-contained command instead: the running node
// binary (process.execPath) plus this package's actual CLI entry script, derived from this
// module's own location rather than process.argv[1] (which differs between the npm-link
// shim and a direct `node bin/context-relay.js` invocation).
function resolveCliScriptPath() {
  const libDir = path.dirname(fileURLToPath(import.meta.url));
  return path.join(libDir, "..", "bin", "context-relay.js");
}

export function resolveHookCommand(provider) {
  return `${shellQuote(process.execPath)} ${shellQuote(resolveCliScriptPath())} hook ${provider}`;
}

// Parses a command line generated by shellQuote() (single-quote-wrapped tokens, with an
// embedded quote written as the '\'' idiom) back into its argv tokens, plus bare
// (unquoted) tokens for anything not quoted at all. Returns null on anything that doesn't
// match this narrow, known shape - callers must treat null as "identity can't be
// established" and fail closed (see isManagedHookCommand below), never guess.
function parseShellQuotedTokens(command) {
  const tokens = [];
  let index = 0;
  const length = command.length;
  while (index < length) {
    while (index < length && /\s/.test(command[index])) {
      index += 1;
    }
    if (index >= length) {
      break;
    }
    if (command[index] !== "'") {
      const start = index;
      while (index < length && !/\s/.test(command[index])) {
        index += 1;
      }
      const token = command.slice(start, index);
      if (token.includes("'")) {
        return null;
      }
      tokens.push(token);
      continue;
    }
    let token = "";
    let sawClosingQuote = false;
    while (index < length && command[index] === "'") {
      index += 1;
      const closeIndex = command.indexOf("'", index);
      if (closeIndex === -1) {
        return null;
      }
      token += command.slice(index, closeIndex);
      index = closeIndex + 1;
      sawClosingQuote = true;
      if (command[index] === "\\" && command[index + 1] === "'") {
        token += "'";
        index += 2;
      }
    }
    if (!sawClosingQuote || (index < length && !/\s/.test(command[index]))) {
      return null;
    }
    tokens.push(token);
  }
  return tokens;
}

// Recognizes commands SHAPED like this tool's own hook - a 4-token generated command that
// invokes a script literally named "context-relay.js" - rather than comparing full path
// IDENTITY against the currently-executing script's resolved path. An earlier version of
// this predicate compared identity (via realpath) against resolveCliScriptPath(), which
// UNDER-matches across an install-path migration: once this package ships to npm, a user
// who installed it as an `npm link`-linked clone and later runs `uninstall`/`status` from
// the published package finds resolveCliScriptPath() now resolves to a different path than
// the one the hook was written with, so identity comparison fails to recognize a hook this
// tool itself wrote. Concretely that meant: `uninstall` silently left the hook installed,
// `status` reported "not installed" while the hook still fired on every Bash call, and once
// the old clone was deleted the orphaned hook errored on every Bash call thereafter.
// Basename matching fixes this because it doesn't care WHICH install wrote the hook, only
// that some install of context-relay did.
//
// Two forms are accepted:
//   1. The exact legacy bare command ("context-relay hook <provider>"), written by a
//      pre-absolute-path version of context-relay - unchanged, a strict 3-token string
//      match.
//   2. A command that parses to exactly 4 tokens where tokens[2] === "hook" and
//      tokens[3] === provider, tokens[0] (the interpreter) is an absolute path whose
//      basename looks like a node executable, tokens[1] (the script-path token) is ALSO an
//      absolute path, and its basename is EXACTLY "context-relay.js" - never the bare
//      basename "context-relay" with no extension. Accepting the bare basename in this
//      4-token form would reopen the exact substring-collision hole this predicate exists
//      to close: "echo context-relay hook claude" also parses to 4 tokens with
//      tokens[1] === "context-relay" and would falsely match. The legacy bare command above
//      stays a 3-token exact-string match only, for the same reason. tokens[0] must ALSO be
//      validated (Copilot finding G): without it, "echo '/tmp/context-relay.js' hook claude"
//      and "/bin/echo /tmp/context-relay.js hook claude" both parse to 4 tokens with a
//      token[1] basename of "context-relay.js" and would falsely match too - see the
//      isManagedHookCommand body below for the full rationale.
// Anything else - including a same-shaped command that fails to parse, has the wrong token
// count, or names a different script (e.g. "/usr/local/bin/context-relay-wrapper hook
// claude", whose basename is "context-relay-wrapper") - returns false.
//
// The residual over-match this predicate still allows is a 4-token command invoking a file
// literally named `context-relay.js` that is NOT this tool - in practice that is only
// another install of context-relay itself, and removing it on `uninstall` is exactly what
// the user asked for. The data-loss asymmetry that motivated the original path-exact
// design (wrongly recognizing an unrelated command as ours, so `uninstall` deletes
// someone else's hook) does not apply to this narrower shape: a generic command invoking
// `curl`, `echo`, or some other unrelated `*.js` script can never collide with it.
//
// NOTE: failing to recognize our own hook is NOT "cosmetic" the way an earlier version of
// this comment claimed - see the migration scenario above. A false negative here leaves an
// orphaned hook that errors on every subsequent Bash call once the stale install is gone.
export function isManagedHookCommand(command, provider) {
  if (typeof command !== "string") {
    return false;
  }
  const trimmed = command.trim();
  if (trimmed === `context-relay hook ${provider}`) {
    return true;
  }

  const tokens = parseShellQuotedTokens(trimmed);
  if (!tokens || tokens.length !== 4) {
    return false;
  }
  const [executableToken, scriptPathToken, hookWord, providerWord] = tokens;
  if (hookWord !== "hook" || providerWord !== provider) {
    return false;
  }
  if (!executableToken || !scriptPathToken) {
    return false;
  }
  // Copilot finding G: the 4-token shape never validated token[0] (the interpreter),
  // only token[1]'s basename - so a foreign hook that merely PASSES a string ending in
  // "context-relay.js" as an ARGUMENT (not as the script actually being executed) was
  // wrongly claimed as ours and deleted by `uninstall`. "echo '/tmp/context-relay.js'
  // hook claude" and "/bin/echo /tmp/context-relay.js hook claude" both parse to 4 tokens
  // with the right token[1] basename and were both false positives before this check -
  // this is the same echo-substring hole the file-level comment above already closed for
  // token[1]'s bare basename, reopened here in token[0]'s shape instead.
  //
  // Both token[0] and token[1] must be ABSOLUTE PATHS - a bare "echo" is never a plausible
  // interpreter path context-relay would generate (resolveHookCommand always emits
  // process.execPath and resolveCliScriptPath(), both absolute). The node-executable check
  // on token[0] is deliberately a loose "basename contains node", not an exact "node"
  // match, for the SAME cross-install-migration reason token[1] is basename-only rather
  // than identity-only: a hook written by a different install may have recorded a
  // differently-named node binary (an nvm-managed path, a Linux "nodejs" binary, a renamed
  // shim) - see the "recognizes a hook pointing at a DIFFERENT install location" test,
  // which deliberately uses "/usr/bin/some-other-node" as token[0] and must stay
  // recognized. Do not tighten this to an exact "node" match without re-checking that test.
  if (!executableToken.startsWith("/") || !path.basename(executableToken).toLowerCase().includes("node")) {
    return false;
  }
  if (!scriptPathToken.startsWith("/")) {
    return false;
  }
  return path.basename(scriptPathToken) === "context-relay.js";
}

function firstToken(command) {
  const match = command.trim().match(/^([A-Za-z0-9_./:-]+)/);
  if (!match) {
    return "";
  }
  return path.basename(match[1]);
}

function hasUnsupportedShellShape(command) {
  return (
    command.includes("\n") ||
    command.includes("\r") ||
    command.includes("<<") ||
    command.includes("$(") ||
    command.includes("`") ||
    SHELL_CONTROL_OPERATOR_PATTERN.test(command)
  );
}

// Copilot findings E/F: naive `command.trim().split(/\s+/)` splits on every literal space,
// including one a real shell would treat as ESCAPED (`\ `) or QUOTED (`'...'`/`"..."`) and
// therefore NOT a word boundary. That mismatch let a value-taking global flag's argument
// swallow the wrong number of words and land subcommand detection on whatever word happened
// to fall at the expected offset - concretely: `git -C /tmp/repo\ log push` naive-splits to
// ['git','-C','/tmp/repo\\','log','push'] (5 words - the escaped space still split), so
// findGitSubcommandIndex skips `-C` and its ostensible one-word value and lands on the
// safe-looking "log" at index 3, while a real shell parses this as ['git','-C','/tmp/repo
// log','push'] (4 words - the directory argument legitimately contains a space) and actually
// runs "push" - a mutating subcommand NOT in SAFE_GIT_SUBCOMMANDS. Same shape, npm family:
// `npm --prefix /tmp/app\ test uninstall pkg` naive-splits to a bogus 6-word form landing on
// "test" while the shell actually runs "uninstall". This is a SAFETY gate, so under-counting
// words in the flag's-value region must never make a mutating subcommand look safe.
//
// parseShellQuotedTokens (above) is NOT the right tool here - it only recognizes the narrow
// shape this tool's OWN shellQuote() generates (an entire token single-quoted, or a bare
// token with no special characters at all) and does not understand backslash-escapes or
// double quotes; run through it, the escaped-space example above tokenizes identically to
// the naive split (still wrong). This is a materially more general problem: an arbitrary
// shell command line written by a human or another tool, which may use backslash escapes or
// either quote style. Handle just enough of POSIX word-splitting to get boundaries right -
// backslash escapes the next character (including a space) outside quotes, single quotes are
// fully literal, double quotes allow backslash to escape a following character - and return
// null when something can't be tokenized with confidence (unterminated quote, a trailing
// backslash with nothing to escape) so the caller fails closed rather than guesses. By the
// time this runs, hasUnsupportedShellShape has already rejected backticks/`$(`/control
// operators/newlines, so this tokenizer only needs to handle quoting and escaping.
function tokenizeShellWords(command) {
  const tokens = [];
  let current = "";
  let hasCurrent = false;
  let index = 0;
  const length = command.length;
  while (index < length) {
    const char = command[index];
    if (/\s/.test(char)) {
      if (hasCurrent) {
        tokens.push(current);
        current = "";
        hasCurrent = false;
      }
      index += 1;
      continue;
    }
    if (char === "\\") {
      if (index + 1 >= length) {
        return null;
      }
      current += command[index + 1];
      hasCurrent = true;
      index += 2;
      continue;
    }
    if (char === "'") {
      const closeIndex = command.indexOf("'", index + 1);
      if (closeIndex === -1) {
        return null;
      }
      current += command.slice(index + 1, closeIndex);
      hasCurrent = true;
      index = closeIndex + 1;
      continue;
    }
    if (char === '"') {
      let innerIndex = index + 1;
      let closed = false;
      while (innerIndex < length) {
        const innerChar = command[innerIndex];
        if (innerChar === '"') {
          closed = true;
          innerIndex += 1;
          break;
        }
        if (innerChar === "\\" && innerIndex + 1 < length) {
          // POSIX double-quote escaping is narrower than backslash-escaping outside
          // quotes: only $ ` " \ (and newline, already rejected earlier by
          // hasUnsupportedShellShape) lose their special meaning to a preceding
          // backslash. Any other character keeps the backslash literally - matching real
          // bash keeps this tokenizer's output identical to what actually executes, rather
          // than silently dropping backslashes a real shell would preserve.
          const nextChar = command[innerIndex + 1];
          if (nextChar === "$" || nextChar === "`" || nextChar === '"' || nextChar === "\\") {
            current += nextChar;
            innerIndex += 2;
            continue;
          }
          current += innerChar;
          innerIndex += 1;
          continue;
        }
        current += innerChar;
        innerIndex += 1;
      }
      if (!closed) {
        return null;
      }
      hasCurrent = true;
      index = innerIndex;
      continue;
    }
    current += char;
    hasCurrent = true;
    index += 1;
  }
  if (hasCurrent) {
    tokens.push(current);
  }
  return tokens;
}

function isAllowedCommandShape(command, executable) {
  const parts = tokenizeShellWords(command);
  if (!parts) {
    // Could not be tokenized with confidence (unterminated quote, dangling backslash) -
    // fail closed. Costs compression on a rare, malformed-looking shape; never wraps one
    // we can't correctly parse the subcommand out of.
    return false;
  }
  if (INTERACTIVE_OR_LONG_RUNNING_PATTERNS.some((pattern) => pattern.test(command))) {
    return false;
  }
  // git and the npm family (npm/pnpm/yarn/bun) accept global flags BEFORE the
  // subcommand (`git -C /path log`, `npm --prefix ./app run build`). This is a SAFETY
  // gate, not just an optimization, so an unrecognized flag shape must fall back to
  // rejecting (-1 from the finder) rather than guessing at a subcommand - see
  // lib/command-shape.js, shared with commandKey in lib/cli.js so this rule has exactly
  // one implementation.
  if (executable === "git") {
    const subcommandIndex = findGitSubcommandIndex(parts);
    if (subcommandIndex === -1) {
      return false;
    }
    // SECURITY: `-c <name>=<value>` is not behaviorally transparent the way `-C <path>`
    // or `--git-dir=<path>` are. findGitSubcommandIndex correctly skips over a leading
    // `-c` to find the real subcommand for STATS ATTRIBUTION (commandKey in lib/cli.js,
    // which only needs to bucket `git -c foo=bar log` alongside `git log`), but this gate
    // must not reuse that same skip to decide SAFETY: `-c` can redefine an alias to run
    // an arbitrary, non-finite command - confirmed live, `git -c alias.log='!sh' log` and
    // `git -c alias.log='!id' log` both land on subcommand "log" (allowlisted) while
    // actually invoking `sh`/`id` instead. Wrapping does not change what executes (the
    // alias would run either way) - what breaks is this gate's contract that a wrapped
    // command is finite and non-interactive; `!sh` is neither, so wrapping it hangs the
    // session on a shell that never exits. `-c` also reaches non-alias config with
    // similar properties (e.g. core.fsmonitor, core.sshCommand), so rather than trying to
    // enumerate every dangerous key, fail closed on ANY leading `-c`: the command is
    // simply left unwrapped, which is always safe and only costs compression on a rare
    // form. Scoped to the leading-flags region (tokens before the resolved subcommand)
    // so a legitimate post-subcommand `-c` - e.g. `git log -c` / `git show -c` for
    // combined merge diffs, a real per-command flag unrelated to global config - is not
    // penalized.
    //
    // --exec-path=<dir> (inline form) was checked for the same escape-hatch shape (it
    // changes where git resolves external dashed subcommands, so a shim `git-log` on that
    // path could hijack `log`) but verified NOT exploitable here: every subcommand in
    // SAFE_GIT_SUBCOMMANDS is a builtin in the git versions available today, so
    // `--exec-path=<dir>` pointing at a directory with a malicious `git-log` does not
    // divert `log` (confirmed live). Left recognized as skippable rather than also failing
    // closed, since there is no live vector for it against this allowlist to trade away.
    // The BARE form (no `=`) is a different, separate problem - see the comment on
    // GIT_BARE_FLAGS in lib/command-shape.js (Copilot finding H): it's a terminal query
    // option, not a passthrough flag, and was removed from the skippable set entirely.
    if (parts.slice(1, subcommandIndex).includes("-c")) {
      return false;
    }
    return SAFE_GIT_SUBCOMMANDS.has(parts[subcommandIndex]);
  }
  if (executable === "npm" || executable === "pnpm") {
    const subcommandIndex = findNpmSubcommandIndex(parts, executable);
    if (subcommandIndex === -1) {
      return false;
    }
    if (parts[subcommandIndex] === "run") {
      return FINITE_PACKAGE_SUBCOMMANDS.has(parts[subcommandIndex + 1]);
    }
    return FINITE_PACKAGE_SUBCOMMANDS.has(parts[subcommandIndex]);
  }
  if (executable === "yarn") {
    const subcommandIndex = findNpmSubcommandIndex(parts, executable);
    if (subcommandIndex === -1) {
      return false;
    }
    return FINITE_YARN_SUBCOMMANDS.has(parts[subcommandIndex]);
  }
  if (executable === "bun") {
    const subcommandIndex = findNpmSubcommandIndex(parts, executable);
    if (subcommandIndex === -1) {
      return false;
    }
    return (
      FINITE_BUN_SUBCOMMANDS.has(parts[subcommandIndex]) ||
      (parts[subcommandIndex] === "run" && FINITE_PACKAGE_SUBCOMMANDS.has(parts[subcommandIndex + 1]))
    );
  }
  if (executable === "cargo") {
    return FINITE_CARGO_SUBCOMMANDS.has(parts[1]);
  }
  if (executable === "deno") {
    return FINITE_DENO_SUBCOMMANDS.has(parts[1]);
  }
  if (executable === "node") {
    return parts[1] === "--test";
  }
  if (executable === "make") {
    return parts.length > 1 && parts.every((part) => !part.includes("="));
  }
  if (executable === "jest") {
    return !parts.some((part) => part === "--watch" || part === "--watchAll");
  }
  return SAFE_COMMANDS.has(executable);
}

export function rewriteShellCommand(command, options = {}) {
  const trimmed = command.trim();
  if (!trimmed) {
    return { changed: false, reason: "empty" };
  }
  if (hasUnsupportedShellShape(command)) {
    return { changed: false, reason: "unsupported-shell-shape" };
  }

  const executable = firstToken(trimmed);
  if (!executable) {
    return { changed: false, reason: "unknown-executable" };
  }
  if (SKIP_COMMANDS.has(executable)) {
    return { changed: false, reason: "skip-command" };
  }
  if (!isAllowedCommandShape(trimmed, executable) && !options.force) {
    return { changed: false, reason: "not-allowlisted" };
  }
  if (AUTH_PATTERNS.some((pattern) => pattern.test(trimmed))) {
    return { changed: false, reason: "sensitive-command" };
  }

  const mode = options.mode || "auto";
  const rewritten = `context-relay run --mode ${mode} -- bash -lc ${shellQuote(command)}`;
  return { changed: true, command: rewritten, reason: "rewritten" };
}

export async function claudeHook(stdin, options = {}) {
  return preToolUseHook(stdin, { ...options, provider: "claude" });
}

export async function codexHook(stdin, options = {}) {
  return preToolUseHook(stdin, { ...options, provider: "codex" });
}

async function preToolUseHook(stdin, options = {}) {
  let payload;
  try {
    payload = JSON.parse(stdin || "{}");
  } catch {
    return "";
  }

  const toolInput = payload.tool_input;
  const command = toolInput?.command;
  if (!toolInput || typeof command !== "string") {
    return "";
  }

  const rewrite = rewriteShellCommand(command, options);
  if (!rewrite.changed) {
    return "";
  }

  const hookSpecificOutput = {
      hookEventName: "PreToolUse",
      updatedInput: {
        ...toolInput,
        command: rewrite.command,
      },
  };
  if (options.provider === "codex") {
    hookSpecificOutput.permissionDecision = "allow";
  }

  return `${JSON.stringify({ hookSpecificOutput })}\n`;
}

function homePath(...segments) {
  return path.join(os.homedir(), ...segments);
}

// Override vars are CONTEXT_RELAY_CLAUDE_HOME / CONTEXT_RELAY_CODEX_HOME (CODEX_HOME as a
// secondary fallback for codex) - NOT CLAUDE_CONFIG_DIR, which this codebase never reads
// and which silently leaves manual testing writing to the real ~/.claude/settings.json.
function claudeDir() {
  return process.env.CONTEXT_RELAY_CLAUDE_HOME || homePath(".claude");
}

function codexDir() {
  return process.env.CONTEXT_RELAY_CODEX_HOME || process.env.CODEX_HOME || homePath(".codex");
}

async function readText(filePath) {
  try {
    return await readFile(filePath, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      return "";
    }
    throw error;
  }
}

async function writeText(filePath, content, dryRun) {
  if (dryRun) {
    return;
  }
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
}

async function removeFile(filePath, dryRun) {
  if (dryRun) {
    return;
  }
  try {
    await unlink(filePath);
  } catch (error) {
    if (error?.code !== "ENOENT") {
      throw error;
    }
  }
}

function appendMarker(content, marker) {
  if (content.includes(marker)) {
    return content.endsWith("\n") ? content : `${content}\n`;
  }
  const prefix = content.trimEnd();
  return `${prefix}${prefix ? "\n\n" : ""}${marker}\n`;
}

function buildClaudeAwareness() {
  return `# Context Relay

Context Relay wraps noisy shell output with compact summaries and local raw-artifact retrieval.

- If a Bash command is automatically rewritten through Context Relay, treat the summary as a navigation aid, not as the full evidence.
- Before making correctness-sensitive claims from compressed output, run the shown \`context-relay retrieve <artifact-id>\` command with \`--grep\` or \`--range\` when a targeted raw slice is enough.
- Use \`context-relay raw -- <command>\` or rerun the original command if exact streaming output is required.
`;
}

function buildCodexAwareness() {
  return `# Context Relay

Context Relay wraps noisy shell output with compact summaries and local raw-artifact retrieval.

- If a Bash command is automatically rewritten through Context Relay, treat the summary as a navigation aid, not as the full evidence.
- Before making correctness-sensitive claims from compressed output, run the shown \`context-relay retrieve <artifact-id>\` command with \`--grep\` or \`--range\` when a targeted raw slice is enough.
- Use \`context-relay raw -- <command>\` when exact streaming output is required.
`;
}

// Shared by both the upsert path (mergeClaudeSettings/mergeCodexHooks) and the removal
// path (removeClaudeHook/removeCodexHook): strips every hook entry that
// isManagedHookCommand recognizes as ours out of a PreToolUse array, dropping any "Bash"
// entry left with zero hooks ONLY when we actually removed a managed hook from it, and
// leaving every non-matching entry (foreign hooks, non-"Bash" matchers) untouched.
//
// Copilot finding D: an earlier version filtered hooks per-entry with .map(), then dropped
// ANY entry afterward whose hooks array had length 0 - regardless of whether that entry's
// hooks were ever touched by the managed-hook filter. That final blanket
// `.filter((entry) => ... entry.hooks.length > 0)` ran over every entry unconditionally,
// including ones the .map() step returned completely unchanged (any non-"Bash" matcher, or
// a "Bash" entry with none of our hooks in it). A foreign entry that simply arrived with an
// empty `hooks` array - or one whose hooks survived filtering just fine but happened to be
// length 0 for an unrelated reason - got silently deleted on every `init`/`uninstall`, even
// though this function never removed anything from it. Data-loss on a routine command, and
// on a DIFFERENT tool's config besides. The fix: only ever drop an entry when this function
// itself actually removed at least one managed hook from it AND nothing is left afterward.
// An entry that was already empty, or whose hooks the managed-hook filter left completely
// unmodified, must survive byte-identical - returned as the exact original object, not even
// a shallow copy.
function stripManagedPreToolUseEntries(preToolUse, provider) {
  const result = [];
  for (const entry of preToolUse) {
    if (entry?.matcher !== "Bash" || !Array.isArray(entry.hooks)) {
      result.push(entry);
      continue;
    }
    const filteredHooks = entry.hooks.filter(
      (hook) => hook?.type !== "command" || !isManagedHookCommand(hook?.command, provider),
    );
    if (filteredHooks.length === entry.hooks.length) {
      // Nothing of ours was in this entry - survive byte-identical, whether hooks was
      // already empty or fully populated with only foreign hooks.
      result.push(entry);
      continue;
    }
    // We actually removed at least one managed hook. Only NOW is dropping the entry for
    // being empty correct - and only if it actually IS empty afterward.
    if (filteredHooks.length > 0) {
      result.push({ ...entry, hooks: filteredHooks });
    }
  }
  return result;
}

function mergeClaudeSettings(existing, hookCommand) {
  let settings = {};
  if (existing.trim()) {
    settings = JSON.parse(existing);
  }
  const hooks = settings.hooks && typeof settings.hooks === "object" ? settings.hooks : {};
  const preToolUse = Array.isArray(hooks.PreToolUse) ? hooks.PreToolUse : [];
  // Upsert, not dedup-or-append: remove every entry shape-matching our own managed hook
  // (per isManagedHookCommand) and then unconditionally append the freshly generated
  // command. Basename-based recognition means a hook left pointing at a DEAD path (a
  // clone-to-npm migration, a repo move, an nvm bump that changed process.execPath) would
  // otherwise read as "already installed" and never get corrected - upserting instead of
  // dedup-or-append self-heals the path on every `init`, leaving no orphan and no
  // duplicate.
  const nextPreToolUse = [
    ...stripManagedPreToolUseEntries(preToolUse, "claude"),
    {
      matcher: "Bash",
      hooks: [{ type: "command", command: hookCommand }],
    },
  ];
  return `${JSON.stringify({ ...settings, hooks: { ...hooks, PreToolUse: nextPreToolUse } }, null, 2)}\n`;
}

function removeClaudeHook(existing) {
  if (!existing.trim()) {
    return "";
  }
  const settings = JSON.parse(existing);
  const hooks = settings.hooks && typeof settings.hooks === "object" ? settings.hooks : {};
  const preToolUse = Array.isArray(hooks.PreToolUse) ? hooks.PreToolUse : [];
  const nextPreToolUse = stripManagedPreToolUseEntries(preToolUse, "claude");
  const nextHooks = { ...hooks };
  if (nextPreToolUse.length > 0) {
    nextHooks.PreToolUse = nextPreToolUse;
  } else {
    delete nextHooks.PreToolUse;
  }
  const nextSettings = { ...settings };
  if (Object.keys(nextHooks).length > 0) {
    nextSettings.hooks = nextHooks;
  } else {
    delete nextSettings.hooks;
  }
  return `${JSON.stringify(nextSettings, null, 2)}\n`;
}

function buildCodexManagedBlock() {
  return `${MANAGED_START}
${CODEX_MARKER}
${MANAGED_END}
`;
}

function mergeManagedBlock(content, block) {
  const pattern = new RegExp(`${MANAGED_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${MANAGED_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n?`);
  if (pattern.test(content)) {
    return content.replace(pattern, block);
  }
  const prefix = content.trimEnd();
  return `${prefix}${prefix ? "\n\n" : ""}${block}`;
}

function removeManagedBlock(content) {
  const pattern = new RegExp(`${MANAGED_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${MANAGED_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n?`);
  return content.replace(pattern, "").trimEnd() + (content.trim() ? "\n" : "");
}

function parseJsonObject(existing) {
  if (!existing.trim()) {
    return {};
  }
  return JSON.parse(existing);
}

function mergeCodexHooks(existing, hookCommand) {
  const payload = parseJsonObject(existing);
  const hooks = payload.hooks && typeof payload.hooks === "object" ? payload.hooks : {};
  const preToolUse = Array.isArray(hooks.PreToolUse) ? hooks.PreToolUse : [];
  // Upsert, not dedup-or-append - see the matching comment in mergeClaudeSettings for why:
  // basename-based recognition would otherwise let a hook stuck on a dead path (migration,
  // repo move, nvm bump) read as "already installed" forever.
  const nextPreToolUse = [
    ...stripManagedPreToolUseEntries(preToolUse, "codex"),
    {
      matcher: "Bash",
      hooks: [
        {
          type: "command",
          command: hookCommand,
          statusMessage: "Wrapping noisy shell output with Context Relay",
        },
      ],
    },
  ];
  return `${JSON.stringify({ ...payload, hooks: { ...hooks, PreToolUse: nextPreToolUse } }, null, 2)}\n`;
}

function removeCodexHook(existing) {
  const payload = parseJsonObject(existing);
  const hooks = payload.hooks && typeof payload.hooks === "object" ? payload.hooks : {};
  const preToolUse = Array.isArray(hooks.PreToolUse) ? hooks.PreToolUse : [];
  const nextPreToolUse = stripManagedPreToolUseEntries(preToolUse, "codex");
  const nextHooks = { ...hooks };
  if (nextPreToolUse.length > 0) {
    nextHooks.PreToolUse = nextPreToolUse;
  } else {
    delete nextHooks.PreToolUse;
  }
  const nextPayload = { ...payload };
  if (Object.keys(nextHooks).length > 0) {
    nextPayload.hooks = nextHooks;
  } else {
    delete nextPayload.hooks;
  }
  return `${JSON.stringify(nextPayload, null, 2)}\n`;
}

export async function installClaude(options = {}) {
  const dryRun = Boolean(options.dryRun);
  const root = claudeDir();
  const settingsPath = path.join(root, "settings.json");
  const awarenessPath = path.join(root, "CONTEXT_RELAY.md");
  const claudeMdPath = path.join(root, "CLAUDE.md");
  const hookCommand = resolveHookCommand("claude");
  const existingSettings = await readText(settingsPath);
  const nextSettings = mergeClaudeSettings(existingSettings, hookCommand);
  const existingClaudeMd = await readText(claudeMdPath);
  const nextClaudeMd = appendMarker(existingClaudeMd, CLAUDE_MARKER);

  await writeText(settingsPath, nextSettings, dryRun);
  await writeText(awarenessPath, buildClaudeAwareness(), dryRun);
  await writeText(claudeMdPath, nextClaudeMd, dryRun);

  return {
    target: "claude",
    dryRun,
    files: [
      { path: settingsPath, action: existingSettings === nextSettings ? "unchanged" : "write" },
      { path: awarenessPath, action: "write" },
      { path: claudeMdPath, action: existingClaudeMd === nextClaudeMd ? "unchanged" : "write" },
    ],
    hook: hookCommand,
  };
}

export async function installCodex(options = {}) {
  const dryRun = Boolean(options.dryRun);
  const root = codexDir();
  const awarenessPath = path.join(root, "CONTEXT_RELAY.md");
  const agentsPath = path.join(root, "AGENTS.md");
  const hooksPath = path.join(root, "hooks.json");
  const hookCommand = resolveHookCommand("codex");
  const existingAgents = await readText(agentsPath);
  const nextAgents = mergeManagedBlock(existingAgents, buildCodexManagedBlock());
  const existingHooks = await readText(hooksPath);
  const nextHooks = mergeCodexHooks(existingHooks, hookCommand);

  await writeText(awarenessPath, buildCodexAwareness(), dryRun);
  await writeText(agentsPath, nextAgents, dryRun);
  await writeText(hooksPath, nextHooks, dryRun);

  return {
    target: "codex",
    dryRun,
    files: [
      { path: awarenessPath, action: "write" },
      { path: agentsPath, action: existingAgents === nextAgents ? "unchanged" : "write" },
      { path: hooksPath, action: existingHooks === nextHooks ? "unchanged" : "write" },
    ],
    hook: hookCommand,
  };
}

export async function statusAgents(args) {
  const allowed = new Set(["--json"]);
  for (const arg of args) {
    if (!allowed.has(arg)) {
      throw new Error(`unknown status option: ${arg}`);
    }
  }
  const rootClaude = claudeDir();
  const rootCodex = codexDir();
  const claudeSettings = await readText(path.join(rootClaude, "settings.json"));
  const claudeMd = await readText(path.join(rootClaude, "CLAUDE.md"));
  const codexAgents = await readText(path.join(rootCodex, "AGENTS.md"));
  const codexHooks = await readText(path.join(rootCodex, "hooks.json"));

  let claudeHookInstalled = false;
  try {
    const settings = claudeSettings.trim() ? JSON.parse(claudeSettings) : {};
    claudeHookInstalled = Boolean(
      settings.hooks?.PreToolUse?.some(
        (entry) =>
          entry?.matcher === "Bash" &&
          entry.hooks?.some((hook) => hook?.type === "command" && isManagedHookCommand(hook?.command, "claude")),
      ),
    );
  } catch {
    claudeHookInstalled = false;
  }
  let codexHookInstalled = false;
  try {
    const hooksPayload = codexHooks.trim() ? JSON.parse(codexHooks) : {};
    codexHookInstalled = Boolean(
      hooksPayload.hooks?.PreToolUse?.some(
        (entry) =>
          entry?.matcher === "Bash" &&
          entry.hooks?.some((hook) => hook?.type === "command" && isManagedHookCommand(hook?.command, "codex")),
      ),
    );
  } catch {
    codexHookInstalled = false;
  }

  return {
    claude: {
      directory: rootClaude,
      hookInstalled: claudeHookInstalled,
      awarenessLinked: claudeMd.includes(CLAUDE_MARKER),
      automaticShellWrapping: claudeHookInstalled,
    },
    codex: {
      directory: rootCodex,
      hookInstalled: codexHookInstalled,
      awarenessLinked: codexAgents.includes(CODEX_MARKER),
      automaticShellWrapping: codexHookInstalled,
    },
  };
}

export async function uninstallAgents(args) {
  const options = {
    claude: false,
    codex: false,
    dryRun: false,
  };
  for (const arg of args) {
    if (arg === "--claude") {
      options.claude = true;
    } else if (arg === "--codex") {
      options.codex = true;
    } else if (arg === "--all") {
      options.claude = true;
      options.codex = true;
    } else if (arg === "--dry-run") {
      options.dryRun = true;
    } else {
      throw new Error(`unknown uninstall option: ${arg}`);
    }
  }
  if (!options.claude && !options.codex) {
    options.claude = true;
    options.codex = true;
  }

  const results = [];
  if (options.claude) {
    const root = claudeDir();
    const settingsPath = path.join(root, "settings.json");
    const claudeMdPath = path.join(root, "CLAUDE.md");
    const awarenessPath = path.join(root, "CONTEXT_RELAY.md");
    const existingSettings = await readText(settingsPath);
    const existingClaudeMd = await readText(claudeMdPath);
    const nextSettings = removeClaudeHook(existingSettings);
    const nextClaudeMd = existingClaudeMd
      .split(/\r?\n/)
      .filter((line) => line.trim() !== CLAUDE_MARKER)
      .join("\n")
      .trimEnd();
    await writeText(settingsPath, nextSettings, options.dryRun);
    await writeText(claudeMdPath, nextClaudeMd ? `${nextClaudeMd}\n` : "", options.dryRun);
    await removeFile(awarenessPath, options.dryRun);
    results.push({
      target: "claude",
      dryRun: options.dryRun,
      files: [
        { path: settingsPath, action: existingSettings === nextSettings ? "unchanged" : "write" },
        { path: claudeMdPath, action: existingClaudeMd === nextClaudeMd ? "unchanged" : "write" },
        { path: awarenessPath, action: "remove" },
      ],
    });
  }
  if (options.codex) {
    const root = codexDir();
    const agentsPath = path.join(root, "AGENTS.md");
    const awarenessPath = path.join(root, "CONTEXT_RELAY.md");
    const hooksPath = path.join(root, "hooks.json");
    const existingAgents = await readText(agentsPath);
    const nextAgents = removeManagedBlock(existingAgents);
    const existingHooks = await readText(hooksPath);
    const nextHooks = removeCodexHook(existingHooks);
    await writeText(agentsPath, nextAgents, options.dryRun);
    await writeText(hooksPath, nextHooks, options.dryRun);
    await removeFile(awarenessPath, options.dryRun);
    results.push({
      target: "codex",
      dryRun: options.dryRun,
      files: [
        { path: agentsPath, action: existingAgents === nextAgents ? "unchanged" : "write" },
        { path: hooksPath, action: existingHooks === nextHooks ? "unchanged" : "write" },
        { path: awarenessPath, action: "remove" },
      ],
    });
  }
  return results;
}

export async function installAgents(args) {
  const options = {
    claude: false,
    codex: false,
    dryRun: false,
  };
  for (const arg of args) {
    if (arg === "--claude") {
      options.claude = true;
    } else if (arg === "--codex") {
      options.codex = true;
    } else if (arg === "--all") {
      options.claude = true;
      options.codex = true;
    } else if (arg === "--dry-run") {
      options.dryRun = true;
    } else {
      throw new Error(`unknown init option: ${arg}`);
    }
  }
  if (!options.claude && !options.codex) {
    options.claude = true;
    options.codex = true;
  }
  const results = [];
  if (options.claude) {
    results.push(await installClaude(options));
  }
  if (options.codex) {
    results.push(await installCodex(options));
  }
  return results;
}
